Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def plt_sinc(x_start, x_dur):
    n_vals = 100
    sinc_vals = np.sinc(np.linspace(-4, 4, n_vals))
    sinc_timing = np.linspace(x_start, x_start+x_dur, n_vals)
    plt.plot(sinc_timing, sinc_vals, linewidth=0.75)

def plt_sin(x_center, x_dur, n_cycles, color):
    n_vals = 1000
    sin_vals = np.sin(n_cycles*2*np.pi*np.linspace(0,1,n_vals))/2
    sin_timing = np.linspace(x_center-x_dur/2, x_center+x_dur/2, n_vals)
    plt.plot(sin_timing, sin_vals, color, linewidth=0.75)

    
def create_simple_pulse_seq(tes, read_time=None, x_axis_duration=None):
    """
    
    """

    n_echos = len(tes)

    if read_time == None:
        read_time = tes[0]/2 - 6

    if n_echos == 1:
        colorlist = ['g']
        if x_axis_duration == None:
            x_axis_duration = tes[-1] + 2.5*read_time
    else:
        colorlist = ['r', 'g', 'b', 'c', 'm', 'y', 'k']
    if x_axis_duration == None:
        x_axis_duration = tes[-1] + 

    # Always do a 2ms sinc pulse for RF excitation (shorter isn't nicely visible)
    plt_sinc(0, 2)
    for echo_idx, echo_val in enumerate(tes):
        plt_sin(echo_val, read_time, 32, colorlist[echo_idx])
    plt.xlim(0,x_axis_duration)

create_simple_pulse_seq([13, 31.26, 49.52], None, 50)
------------------


[0;36m  Cell [0;32mIn[2], line 31[0;36m[0m
[0;31m    x_axis_duration = tes[-1] +[0m
[0m                                ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


